### ISSUE TITLE
Swarm replication sometimes just does not happen

### ISSUE THREAD

**Issue by pfrazee** [joehand/hypercloud#16]
I've observed this on local and remote tests. It seems like there's a roughly 50/50 chance that an archive will actually replicate.

**Comment by pfrazee** [comment]
I have two clues for the causes of this. These dumps come from one session, in which I had the server in one thread, and the tests-client running in another. [Here are the logs](https://gist.github.com/pfrazee/40ae2095dceea56a5eff2c67c6f7a0d5).

1. There are error conditions with RAF which are causing connections to abort.

```
Wed, 28 Dec 2016 02:26:30 GMT hypercore-replicate chan=af36f8..8f read() get failed, aborting Error: File is closed
    at RandomAccessFile.read (/Users/paulfrazee/pubpeer/hypercloud/node_modules/random-access-file/index.js:68:27)
    at onnode (/Users/paulfrazee/my/hypercore/lib/storage.js:65:21)
    at /Users/paulfrazee/my/hypercore/node_modules/subleveldown/node_modules/levelup/lib/levelup.js:230:7
```

and

```
Wed, 28 Dec 2016 02:26:30 GMT hypercore-replicate chan=e6fa9d..0a write() error Error: File is closed
    at RandomAccessFile.write (/Users/paulfrazee/pubpeer/hypercloud/node_modules/random-access-file/index.js:93:27)
    at lookup (/Users/paulfrazee/my/hypercore/lib/storage.js:54:36)
    at Storage.put (/Users/paulfrazee/my/hypercore/lib/storage.js:26:3)
    at writeStorage (/Users/paulfrazee/my/hypercore/lib/feed.js:293:18)
    at /Users/paulfrazee/my/hypercore/node_modules/levelup-defaults/node_modules/levelup/lib/levelup.js:320:9
```

This seems odd and a possible cause, but I'm not totally sure they're conclusive. In the client log, you'll see the test fails after synchronization of a dat from the server to the client times out. There are multiple channels closed there -- more than the 2 RAF files explain.

 2. There are signs of multiple channel-sessions being created, simultaneously, between the peers. Should that be happening? I'm wondering if that shouldn't be happening, and it's creating confusion.

cc @mafintosh

**Comment by pfrazee** [comment]
More evidence that RAF failures aren't the only cause: I've gotten failed syncs without them.

**Comment by pfrazee** [comment]
Multiple bugs involved. In hot pursuit

**Comment by pfrazee** [comment]
This may be solved!
