### ISSUE TITLE
Start Errors after install on debain 

### ISSUE THREAD

**Issue by freedomtrain** [joehand/hypercloud#84]
I have installed hypercloud on debain and when I receiving some errors the below errors that are preventing hypercloud from starting 

Detected node version 6, transpiling async to generators
Data directory: ./.hypercloud
body-parser deprecated undefined extended: provide extended option index.js:35:22
/var/www/vhosts/hamer.io/cloud.hamer.io/hypercloud/node_modules/hypercloud-ui-vanilla/index.js:37
  app.get('/', async ({req, res}) => {
                     ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/var/www/vhosts/hamer.io/cloud.hamer.io/hypercloud/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/var/www/vhosts/hamer.io/cloud.hamer.io/hypercloud/index.js:135:13)
    at Object.<anonymous> (/var/www/vhosts/hamer.io/cloud.hamer.io/hypercloud/bin.js:5:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:

**Comment by pfrazee** [comment]
I'll check into this, thanks

**Comment by pfrazee** [comment]
Hey Fred, what version of node are you using? Is it 6?

**Comment by freedomtrain** [comment]
node -v
v7.7.1

**Comment by pfrazee** [comment]
That's odd, it's detecting v6. Try commenting out everything in https://github.com/datprotocol/hypercloud/blob/master/nodecompat.js and see if it works
